### ISSUE TITLE
Lots of region-related things are hard-coded

### ISSUE THREAD

**Issue by kvablack** [autognc/bran#3]
I have to go in and edit [this line](https://github.com/autognc/bran/blob/159243c680a4aa10118287053e356a2c28f4ae46/bran/bran.py#L73) in order to use bran on the east coast.

**Comment by kvablack** [comment]
This also applies to the AMI, currently the Ubuntu Deep Learning AMI is hardcoded but it has a different ID in other regions.

**Comment by kvablack** [comment]
Ran into a similar issue with the keypair -- a keypair is only valid for the region in which it's created, so the downloaded keypair from S3 didn't work. Storing private keys on S3 probably isn't a great idea anyway, since transmitting them over the internet over and over is pretty bad for security. I feel like a better solution might be storing them locally per-user in `~/.aws/<region>/keypair.pem`, and creating a new one each time a user doesn't have one yet.

**Comment by cSchubes** [comment]
Per the region related things: we intentionally hardcoded it for now because we want everything to run in the same AWS region. It's a cost saving measure - if you transfer data between S3 and EC2 within the same region its free, whereas transferring between regions is charged. Although S3 is a "regionless" service your buckets still have a home region.

If/when we open source this, we will want that to be configurable though.

Per keypair stuff: I don't know much about EC2/AWS keypairs, but it seems reasonable that storing them in S3 isn't ideal. I'll wait for @nihaldhamani to comment on this.

**Comment by nihaldhamani** [comment]
We will be using us-west-1 for all our aws resources for now.

For keypair: Yes that is ideally how you should do it but we had made a decision early on to sacrifice the best security practices to offer more flexibility. This way, if one authorized user starts a training and that ec2 instance needs to be accessed/stopped by another user if the first one isn't available then they would be able to with this way.
